version: 0.2
phases:
  build:
    commands:
      - echo started Build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully..
artifacts:
  files:
    - target/hello-world.jar
  discard-paths: yes